### ISSUE TITLE
Is there an example of unmanaged powershell in Rust?

### ISSUE THREAD

**Issue by A1-exe** [trickster0/Hacking-With-Rust#29]
In the offensive nim repo there is an example of how to use nim to interact with unmanaged powershell.
https://github.com/byt3bl33d3r/OffensiveNim/blob/master/src/execute_powershell_bin.nim

I am wondering if this has been done in Rust? Is this even possible to do in purely Rust?

**Comment by trickster0** [comment]
unsure, in general in Red team, we avoid powershell so i havent checked.
