### ISSUE TITLE
Ekko-rs crashes

### ISSUE THREAD

**Issue by 1N73LL1G3NC3x** [trickster0/Hacking-With-Rust#39]
The program crashes 6 minutes after launch on a completely updated Windows (it works stably on PC without a system updates from the 2022).
![00176799-24FF-4F37-BDD6-BED1F9BC5EDA](https://github.com/trickster0/OffensiveRust/assets/143444649/4ace9b71-d56d-4460-9204-026efb53a0df)

**Comment by trickster0** [comment]
It is most likely a known race time condition. Check ekkoex from paul. I have made it in rust but haven’t published it since it is easy to fix.

**Comment by 1N73LL1G3NC3x** [comment]
Sorry, could you please send me the code with the fixes. My level of knowledge is far from yours) I undertake that it will not be shared publicly, if this is the problem.

**Comment by trickster0** [comment]
No sorry, I don't think I can.
